apiVersion: v1
kind: Pod
metadata:
  name: loadbalancer-service
  labels:
    name: my-app
    demo: service
spec:
  containers:
    - name: nginxcont
      image: nginx
      ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: LoadBalancer
  selector:
    name: my-app
    demo: service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

