apiVersion: v1
kind: Pod
metadata:
  name: nodeport-Service
  labels:
    app: my-app
    environment: dev
spec:
  containers:
    - name: nginxcont
      image: nginx
      port:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: np-Service
spec:
  type: NodePort
  selector:
    app: my-app
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 

    
